// src/app/playground/code-canvas/components/primitives/ExportPanel.tsx
'use client';

import React, { useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { cn } from '@/lib/utils';
import type { ExportPanelProps, ExportFormat } from '../types';
import { getSizeConfig, CANVAS_ANIMATIONS } from '../types';

/**
 * Export option configuration
 */
interface ExportOption {
  id: ExportFormat;
  label: string;
  description: string;
  icon: React.ReactNode;
}

const EXPORT_OPTIONS: ExportOption[] = [
  {
    id: 'code',
    label: 'Copy Code',
    description: 'Copy to clipboard',
    icon: (
      <svg
        className="w-5 h-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
        />
      </svg>
    ),
  },
  {
    id: 'codesandbox',
    label: 'CodeSandbox',
    description: 'Open in CodeSandbox',
    icon: (
      <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
        <path d="M2 6l10.455-6L22.91 6 23 17.95 12.455 24 2 18V6zm2.088 2.481v4.757l3.345 1.86v3.516l3.972 2.296v-8.272L4.088 8.481zm16.739 0l-7.317 4.157v8.272l3.972-2.296v-3.516l3.345-1.86V8.481zM5.134 6.601l7.303 4.144 7.32-4.18-3.871-2.197-3.41 1.945-3.43-1.968L5.134 6.6z" />
      </svg>
    ),
  },
  {
    id: 'stackblitz',
    label: 'StackBlitz',
    description: 'Open in StackBlitz',
    icon: (
      <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
        <path d="M10.797 14.182H3.635L16.728 0l-3.525 9.818h7.162L7.272 24l3.525-9.818z" />
      </svg>
    ),
  },
  {
    id: 'download',
    label: 'Download',
    description: 'Download as file',
    icon: (
      <svg
        className="w-5 h-5"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          strokeWidth={2}
          d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"
        />
      </svg>
    ),
  },
];

/**
 * Generate CodeSandbox URL
 */
function openInCodeSandbox(code: string): void {
  const parameters = {
    files: {
      'package.json': {
        content: {
          dependencies: {
            react: '^18.2.0',
            'react-dom': '^18.2.0',
          },
        },
      },
      'App.tsx': {
        content: code,
      },
      'index.tsx': {
        content: `import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

const root = createRoot(document.getElementById('root')!);
root.render(<App />);
`,
      },
      'index.html': {
        content: `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`,
      },
    },
  };

  const encoded = btoa(JSON.stringify(parameters))
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');

  window.open(
    `https://codesandbox.io/api/v1/sandboxes/define?parameters=${encoded}`,
    '_blank',
  );
}

/**
 * Generate StackBlitz URL
 */
function openInStackBlitz(code: string): void {
  const form = document.createElement('form');
  form.method = 'POST';
  form.action = 'https://stackblitz.com/run';
  form.target = '_blank';

  const projectData = {
    'project[title]': 'Generated Component',
    'project[description]': 'Component generated by Code Canvas',
    'project[template]': 'create-react-app',
    'project[dependencies]': JSON.stringify({
      react: '^18.2.0',
      'react-dom': '^18.2.0',
    }),
    'project[files][src/App.tsx]': code,
    'project[files][src/index.tsx]': `import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

const root = createRoot(document.getElementById('root')!);
root.render(<App />);
`,
    'project[files][public/index.html]': `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`,
  };

  Object.entries(projectData).forEach(([key, value]) => {
    const input = document.createElement('input');
    input.type = 'hidden';
    input.name = key;
    input.value = value;
    form.appendChild(input);
  });

  document.body.appendChild(form);
  form.submit();
  document.body.removeChild(form);
}

/**
 * Download code as file
 */
function downloadCode(code: string): void {
  const blob = new Blob([code], { type: 'text/typescript' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = 'Component.tsx';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export panel component
 */
export function ExportPanel({
  code,
  onExport,
  size = 'default',
  className,
}: ExportPanelProps) {
  const sizeConfig = getSizeConfig(size);
  const [isOpen, setIsOpen] = useState(false);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleExport = useCallback(
    async (format: ExportFormat) => {
      switch (format) {
        case 'code':
          try {
            await navigator.clipboard.writeText(code);
            setCopiedId('code');
            setTimeout(() => setCopiedId(null), 2000);
          } catch {
            // Fallback
            const textarea = document.createElement('textarea');
            textarea.value = code;
            document.body.appendChild(textarea);
            textarea.select();
            document.execCommand('copy');
            document.body.removeChild(textarea);
            setCopiedId('code');
            setTimeout(() => setCopiedId(null), 2000);
          }
          break;
        case 'codesandbox':
          openInCodeSandbox(code);
          break;
        case 'stackblitz':
          openInStackBlitz(code);
          break;
        case 'download':
          downloadCode(code);
          break;
      }
      onExport(format);
    },
    [code, onExport],
  );

  return (
    <div className={cn('relative', className)}>
      {/* Export button */}
      <motion.button
        type="button"
        onClick={() => setIsOpen(!isOpen)}
        whileHover={{ scale: 1.02 }}
        whileTap={{ scale: 0.98 }}
        className={cn(
          'flex items-center gap-2 px-4 py-2 rounded-lg',
          'bg-gray-900 dark:bg-white',
          'text-white dark:text-gray-900',
          'font-medium',
          'hover:bg-gray-800 dark:hover:bg-gray-100',
          'transition-colors duration-150',
          !code && 'opacity-50 cursor-not-allowed',
        )}
        style={{ fontSize: sizeConfig.fontSize }}
        disabled={!code}
      >
        <svg
          className="w-4 h-4"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z"
          />
        </svg>
        Export
        <svg
          className={cn(
            'w-4 h-4 transition-transform duration-150',
            isOpen && 'rotate-180',
          )}
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M19 9l-7 7-7-7"
          />
        </svg>
      </motion.button>

      {/* Dropdown */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: -10, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: -10, scale: 0.95 }}
            transition={CANVAS_ANIMATIONS.fast}
            className={cn(
              'absolute right-0 top-full mt-2 z-50',
              'w-56 p-2 rounded-xl',
              'bg-white dark:bg-gray-900',
              'border border-gray-200 dark:border-gray-800',
              'shadow-lg',
            )}
          >
            {EXPORT_OPTIONS.map((option) => (
              <button
                key={option.id}
                type="button"
                onClick={() => {
                  handleExport(option.id);
                  if (option.id !== 'code') {
                    setIsOpen(false);
                  }
                }}
                className={cn(
                  'w-full flex items-center gap-3 p-3 rounded-lg',
                  'text-left',
                  'transition-colors duration-150',
                  copiedId === option.id
                    ? 'bg-green-50 dark:bg-green-900/20'
                    : 'hover:bg-gray-100 dark:hover:bg-gray-800',
                )}
              >
                <span
                  className={cn(
                    copiedId === option.id
                      ? 'text-green-600 dark:text-green-400'
                      : 'text-gray-500 dark:text-gray-400',
                  )}
                >
                  {copiedId === option.id ? (
                    <svg
                      className="w-5 h-5"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                  ) : (
                    option.icon
                  )}
                </span>
                <div className="flex-1 min-w-0">
                  <p
                    className={cn(
                      'font-medium',
                      copiedId === option.id
                        ? 'text-green-700 dark:text-green-300'
                        : 'text-gray-900 dark:text-gray-100',
                    )}
                    style={{ fontSize: sizeConfig.fontSize }}
                  >
                    {copiedId === option.id ? 'Copied!' : option.label}
                  </p>
                  <p
                    className="text-gray-500 dark:text-gray-400 truncate"
                    style={{ fontSize: sizeConfig.fontSize - 2 }}
                  >
                    {option.description}
                  </p>
                </div>
              </button>
            ))}
          </motion.div>
        )}
      </AnimatePresence>

      {/* Backdrop to close dropdown */}
      {isOpen && (
        <button
          type="button"
          className="fixed inset-0 z-40 cursor-default bg-transparent border-0"
          onClick={() => setIsOpen(false)}
          onKeyDown={(e) => e.key === 'Escape' && setIsOpen(false)}
          aria-label="Close export menu"
          tabIndex={-1}
        />
      )}
    </div>
  );
}

export default ExportPanel;
