import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';
import { AppProvider } from '@/providers/app';
import FancyNav from '@/components/FancyNav/FancyNav';
import { SplashConfig, SplashScreenWrapper } from '@/components/Splash';
import { FiCommand } from 'react-icons/fi';
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const menuItems = [
  { label: 'Home', href: '/', current: false },
  { label: 'About', href: '/about', current: false },
  { label: 'Resources', href: '/resources', current: true }, // Active menu item
  { label: 'Contact', href: '/contact', current: false },
  { label: 'Login', href: '/login', current: false, className: 'text-red-500' }, // Additional styling
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const splashConfig: Partial<SplashConfig> = {
    themable: true,
    backgroundColor: 'bg-slate-50 dark:bg-slate-950',
    containerSize: 'w-32 h-32',
    containerShape: 'rounded-full',
    frequency: 'once-per-session',
    // frequency: 'always',
    icon: <FiCommand className="text-4xl text-blue-500" />,
    message: 'Loading, please wait...',
    animation: 'grow',
    // animation: 'slide',
    displayDuration: 20000,
  };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SplashScreenWrapper config={splashConfig}>
          <AppProvider>
            <div className="bg-gray-800 flex items-center justify-start">
              <FancyNav
                menuItems={menuItems}
                alignment="left" // Can be 'left' | 'center' | 'right'
                magicLineColor="bg-gray-500"
                magicLineHoverColor="bg-yellow-200"
                containerWidth="w-full max-w-[370px]" // Makes it responsive
              />
            </div>
            <Link href="/playground/box">Playground Box</Link>
            {'  '}
            &nbsp; &nbsp; &nbsp;
            <Link href="/playground/pagemode">Playground Pagemode</Link>
            &nbsp; &nbsp; &nbsp;
            <Link href="/playground/typo">Playground Typography</Link>
            &nbsp; &nbsp; &nbsp;
            <Link href="/demo">Demo</Link>
            {children}
          </AppProvider>
        </SplashScreenWrapper>
      </body>
    </html>
  );
}
