import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';
import { AppProvider } from '@/providers/app';
import FancyNav from '@/components/FancyNav/FancyNav';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const menuItems = [
  { label: 'Home', href: '/', current: false },
  { label: 'About', href: '/about', current: false },
  { label: 'Resources', href: '/resources', current: true }, // Active menu item
  { label: 'Contact', href: '/contact', current: false },
  { label: 'Login', href: '/login', current: false, className: 'text-red-500' }, // Additional styling
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <div className="bg-gray-800 flex items-center justify-start">
            <FancyNav
              menuItems={menuItems}
              alignment="left" // Can be 'left' | 'center' | 'right'
              magicLineColor="bg-gray-500"
              magicLineHoverColor="bg-yellow-200"
              containerWidth="w-full max-w-[370px]" // Makes it responsive
            />
          </div>
          <Link
            href="/playground/box"
            className="text-white hover:text-gray-300"
          >
            Playground Box
          </Link>
          {'  '}
          &nbsp; &nbsp; &nbsp;
          <Link
            href="/playground/pagemode"
            className="text-white hover:text-gray-300"
          >
            Playground Pagemode
          </Link>
          &nbsp; &nbsp; &nbsp;
          <Link
            href="/playground/typo"
            className="text-white hover:text-gray-300"
          >
            Playground Typography
          </Link>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
