name: CI Pipeline

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  REPOSITORY_NAME: mediaapp

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: staging  # Ensure the staging branch is checked out

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      # Build and Push Backend
      - name: Build Backend Docker image
        run: |
          docker build --platform linux/amd64  --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.REPOSITORY_NAME}}:web-app-latest -f Dockerfile.prod .

      - name: Push Backend Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.REPOSITORY_NAME}}:web-app-latest
     # Build and Push Nginx Proxy Image
      # - name: Build Nginx Proxy Docker image
      #   run: |
      #     docker build --platform linux/amd64 -t ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-proxy:latest -f nginx-proxy/Dockerfile ./nginx-proxy
      # - name: Push Nginx Proxy Docker image to Docker Hub
      #   run: |
      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-proxy:latest
      # - name: Push Backend Docker image to Docker Hub
      #   run: |
      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.REPOSITORY_NAME}}:web-app-${{ github.sha }}
      #     docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.REPOSITORY_NAME}}:web-app-latest

# .github/workflows/ci-docker-hub.yml